---
resources:
  - name: repository
    type: git
    source:
      uri: https://github.com/ArchanaChillala/semver-test.git
      username: ((username))
      password: ((password))

  - name: version
    type: semver
    source:
      driver: git
      uri: https://github.com/ArchanaChillala/semver-test.git
      username: ((username))
      password: ((password))
      branch: master
      file: version
      private_key: ((github-private-key))
      initial_version: 1.1.0

jobs:
  - name: bump-patch
    plan:
    - get: repository
      trigger: true
    - put: version
      params:
        bump: patch
